remove openssl build
bottlerocket-os/bottlerocket-sdk pull request #111
Opened 2023-06-08 20:36 UTC by bcressey

**Issue number:**
N/A

**Description of changes:**
This build was used by the update operator and the test system, both of which have now switched to rustls.

**Testing done:**
Verified that the SDK built and the musl sys-root was back to just kernel headers, musl, and libunwind.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2023-06-08 20:41 UTC, cbgbt approved these changes
:crab:

2023-06-08 20:56 UTC, jpculp approved these changes

2023-06-08 21:26 UTC, jpmcb approved these changes
🕺🏼

2023-06-09 19:16 UTC, webern requested changes
This is just to remove the static build, right? I needed the regular fedora install of openssl for something during the twoliter prototyping. Should I look into what that was, or is it irrelevant for this PR?

2023-06-12 01:47 UTC, bcressey commented
> This is just to remove the static build, right? I needed the regular fedora install of openssl for something during the twoliter prototyping. Should I look into what that was, or is it irrelevant for this PR?

Right, the "host" openssl build from Fedora will still be present.

2023-06-12 17:05 UTC, arnaldo2792 approved these changes

2023-06-12 20:09 UTC, webern approved these changes
The openssl dependency I was thinking of occurs when `tuftool` generates a default root key in `pubsys-setup`. We will find another way to do this.

2023-06-12 21:09 UTC, merged