Update dependencies
bottlerocket-os/bottlerocket-sdk pull request #81
Opened 2022-08-04 16:05 UTC by zmrow

**Description of changes:**
```
    license-tool: Update dependencies
    
    This updates all the crate dependencies.
```

```
    license-scan: Update dependencies
    
    This updates all the dependencies for `license-scan` and handles the
    associated `anyhow` API changes in `main.rs`.
```

**Testing done:**
* Unit tests for `license-scan` continue to pass
* Both projects build

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-08-04 16:28 UTC, bcressey approved these changes

2022-08-04 18:54 UTC, cbgbt approved these changes

2022-08-05 00:10 UTC, jpculp requested changes
Before we merge, we'll want to update the `clarify.toml` files.

2022-09-23 18:57 UTC, bcressey commented
This was superseded by #82, so I'll go ahead and close it.

2022-09-23 18:57 UTC, closed without merging